version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: travel_aggregator_db
    restart: always
    environment:
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_password
      POSTGRES_DB: travel_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel_user -d travel_aggregator"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: