import { AccommodationType } from '@prisma/client'

// Database types (generated by Prisma)
export type { Destination, Flight, Accommodation, AccommodationType } from '@prisma/client'

// Form types per la ricerca
export interface SearchFormData {
  destination: string
  checkIn: Date
  checkOut: Date
  guests: number
  budget: number
  preferences: UserPreferences
}

export interface UserPreferences {
  accommodationType: AccommodationType[]
  priceRange: 'budget' | 'mid' | 'luxury'
  amenities: string[]
  flightPreference: 'cheapest' | 'shortest' | 'best_time'
}

// Types per i risultati della ricerca
export interface TravelPackage {
  id: string
  flight: FlightDetails
  accommodation: AccommodationDetails
  totalPrice: number
  score: number
  savings?: number
}

export interface FlightDetails {
  id: string
  airline: string
  flightNumber: string
  origin: string
  destination: string
  departureTime: Date
  arrivalTime: Date
  duration: number
  price: number
  aircraft?: string | null
}

export interface AccommodationDetails {
  id: string
  name: string
  type: AccommodationType
  address: string
  rating: number
  pricePerNight: number
  totalNights: number
  totalPrice: number
  amenities: string[]
  imageUrl?: string | null
  description?: string | null
}

// API Response types
export interface SearchResponse {
  packages: TravelPackage[]
  total: number
  searchTime: number
  filters: SearchFilters
}

export interface SearchFilters {
  priceRange: { min: number; max: number }
  ratings: number[]
  airlines: string[]
  accommodationTypes: AccommodationType[]
}

// Utility types
export interface SearchParams {
  destination: string
  checkIn: string
  checkOut: string
  guests: string
  budget: string
  preferences?: string
}

export interface ScoringWeights {
  price: number
  rating: number
  amenities: number
  flightTime: number
  location: number
}